### ISSUE TITLE
TypeError: result[key].replace is not a function

### ISSUE THREAD

**Issue by arun21** [cermak-petr/act-mysql-insert#4]
Hi, I'm using Apify, web-scraper task (apify/web-scraper) and using a webhook petr_cermak/MySQL-insert). When the dataset it gets from the web scraper task when it succeeded, I get below error

Is there a format of the dataset it should be passed to  petr_cermak/MySQL-insert task, How I send is as below.. in json form

    return {
        address : url,
        name,
        volume,
        price
    };

This json is passed as dataset to MySQL-insert task with connection information but I get below error, whatever dataset I pass

TypeError: result[key].replace is not a function
2021-01-12T01:40:32.085Z     at _.each (/usr/src/app/main.js:63:45)
2021-01-12T01:40:32.091Z     at Function._.each._.forEach (/usr/src/app/node_modules/underscore/underscore.js:186:9)
2021-01-12T01:40:32.092Z     at addValueString (/usr/src/app/main.js:57:11)
2021-01-12T01:40:32.092Z     at createInsert (/usr/src/app/main.js:81:18) 

Could you please let me know which format of the dataset, MySQL-insert task expects?

**Comment by fferoz** [comment]
Hi 
I am getting same error whenever the mysql-insert actor gets triggered. I am using Webhook of puppeteer actor. I'm new to Apify so any help would be highly appreciated. 

Thanks!
@arun21 
@cermak-petr

**Comment by metalwarrior665** [comment]
Hello, We will look into the problem shortly

**Comment by fferoz** [comment]
@metalwarrior665 thank you for your response.

**Comment by fferoz** [comment]
@metalwarrior665 Hi, 

Please let me know once you've any update for me, here! 

Thanks!

**Comment by pocesar** [comment]
@fferoz it's being fixed

**Comment by fferoz** [comment]
@pocesar Hi, 

Do we have any update here? 

Thank you!

**Comment by pocesar** [comment]
@fferoz this is fixed and released as `beta` on the platform. when #10 is merged, it will be available on `latest`
